AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Job scraping Lambda built from backend/go/cmd/lambda.

Globals:
  Function:
    Runtime: provided.al2023
    Architectures:
      - arm64
    Timeout: 900
    MemorySize: 128

Resources:
  JobScraperFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: JobScraperLambda
      CodeUri: .
      Handler: bootstrap
      Description: Runs the Go scraper pipeline inside Lambda.
      Environment:
        Variables:
          QUERY: "software engineer"
          DEBUG_OUTPUT: ""
          API_DRY_RUN: ""
          USE_MOCK_JOBS: ""
          DYNAMODB_ENDPOINT: "http://host.docker.internal:8000"
          AWS_ACCESS_KEY_ID: "dummy"
          AWS_SECRET_ACCESS_KEY: "dummy"
          AWS_REGION: "us-west-2"
          LLM_PROMPT_PATH: "/var/task/prompt.txt"
          OPENAI_API_KEY: "" # Ensure this is set in env.json or actual environment for real runs
          API_SERVER_URL: "http://host.docker.internal:8080/api"
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /scrape
            Method: post
    Metadata:
      BuildMethod: makefile

Outputs:
  JobScraperFunctionArn:
    Description: ARN of the deployed Lambda function.
    Value: !GetAtt JobScraperFunction.Arn
