AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Job scraping Lambda built from backend/go/cmd/lambda.

Parameters:
  Query:
    Type: String
    Default: software developer
    Description: Search query passed to the scraper.
  DebugOutput:
    Type: String
    Default: "false"
    AllowedValues: ["true", "false"]
    Description: Enable verbose debug logging.
  ApiDryRun:
    Type: String
    Default: "false"
    AllowedValues: ["true", "false"]
    Description: Skip OpenAI/DynamoDB calls when true.
  UseJobIDFile:
    Type: String
    Default: "false"
    AllowedValues: ["true", "false"]
    Description: Enable local file caching (off in Lambda).
  UseS3JobIDFile:
    Type: String
    Default: "false"
    AllowedValues: ["true", "false"]
    Description: Sync the job ID cache with S3 when enabled.
  OpenAIAPIKey:
    Type: String
    NoEcho: true
    Description: API key for OpenAI requests.
  AWSRegion:
    Type: String
    Default: us-west-2
    Description: AWS region used by the SDK.
  DynamoTableName:
    Type: String
    Default: Jobs
    Description: Name of the DynamoDB table storing jobs.
  DynamoEndpoint:
    Type: String
    Default: ""
    Description: Optional override for local DynamoDB endpoint.

Globals:
  Function:
    Runtime: provided.al2023
    Architectures:
      - arm64
    Timeout: 900
    MemorySize: 128

Resources:
  JobScraperFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: JobScraperLambda
      CodeUri: .
      Handler: bootstrap
      Description: Runs the Go scraper pipeline inside Lambda.
      Environment:
        Variables:
          QUERY: !Ref Query
          DEBUG_OUTPUT: !Ref DebugOutput
          API_DRY_RUN: !Ref ApiDryRun
          USE_JOB_ID_FILE: !Ref UseJobIDFile
          USE_S3_JOB_ID_FILE: !Ref UseS3JobIDFile
          OPENAI_API_KEY: !Ref OpenAIAPIKey
          AWS_REGION: !Ref AWSRegion
          DYNAMODB_TABLE_NAME: !Ref DynamoTableName
          DYNAMODB_ENDPOINT: !Ref DynamoEndpoint
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /scrape
            Method: post
    Metadata:
      BuildMethod: makefile

Outputs:
  JobScraperFunctionArn:
    Description: ARN of the deployed Lambda function.
    Value: !GetAtt JobScraperFunction.Arn
